// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZxczHQ5vwb_j750O3ZVnMxvzCXUTE5g',
    appId: '1:369037690588:web:82475bb143e5f4bea85619',
    messagingSenderId: '369037690588',
    projectId: 'eyes-up-6509a',
    authDomain: 'eyes-up-6509a.firebaseapp.com',
    storageBucket: 'eyes-up-6509a.appspot.com',
    measurementId: 'G-72JZST4GW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbu4GRJPHSqNuhMmVVj6xn6k-sWyTmFLU',
    appId: '1:369037690588:android:8f9d7071597a8900a85619',
    messagingSenderId: '369037690588',
    projectId: 'eyes-up-6509a',
    storageBucket: 'eyes-up-6509a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNCOtE0kNg46FyhYb_CTY59pw2CG8yDo',
    appId: '1:369037690588:ios:715c6ae3f9ceee26a85619',
    messagingSenderId: '369037690588',
    projectId: 'eyes-up-6509a',
    storageBucket: 'eyes-up-6509a.appspot.com',
    iosBundleId: 'com.example.p01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNCOtE0kNg46FyhYb_CTY59pw2CG8yDo',
    appId: '1:369037690588:ios:715c6ae3f9ceee26a85619',
    messagingSenderId: '369037690588',
    projectId: 'eyes-up-6509a',
    storageBucket: 'eyes-up-6509a.appspot.com',
    iosBundleId: 'com.example.p01',
  );
}
